# HawkEye license header checker config (v6+)

baseDir = "."

inlineHeader = """\
Copyright © 2024–2026 Faith Frontier Ecclesiastical Trust. All rights reserved.
PROPRIETARY — See LICENSE.\
"""

strictCheck = true
useDefaultExcludes = true
useDefaultMapping  = true

includes = [
  "**/*.py",
  "**/*.js",
  "**/*.ts",
  "**/*.tsx",
  "**/*.jsx",
  "**/*.go",
  "**/*.rs",
  "**/*.java",
  "**/*.kt",
  "**/*.c",
  "**/*.h",
  "**/*.cpp",
  "**/*.hpp",
  "**/*.sh",
  "**/*.yaml",
  "**/*.yml"
]

excludes = [
  "**/node_modules/**",
  "**/.venv/**",
  "**/venv/**",
  "**/dist/**",
  "**/build/**",
  "**/.git/**"
]
